[service]
name = "postgres"
description = "PostgreSQL - open source relational database"
url = "https://www.postgresql.org/docs/"
image = "docker.io/library/postgres:17-alpine"
architecture = ["amd64", "arm64"]
kind = "infrastructure"
note = "psql postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@127.0.0.1:$RYRA_PORT_TCP/$POSTGRES_DB  # connect"

[requirements.ram]
min = 128
recommended = 256

[[ports]]
name = "tcp"
container_port = 5432

[[volumes]]
name = "data"
mount_path = "/var/lib/postgresql/data"

[[env]]
name = "POSTGRES_USER"
value = "postgres"
kind = "prompted"
prompt = "Database admin username"

[[env]]
name = "POSTGRES_DB"
value = "postgres"
kind = "prompted"
prompt = "Default database name"

[[env]]
name = "POSTGRES_PASSWORD"
value = "{{secret.postgres_password}}"

[integrations]
auth = []
smtp = false
