[service]
name = "whoami"
description = "Traefik whoami - simple HTTP request echo"
url = "https://github.com/traefik/whoami"
architecture = ["amd64", "arm64"]

[[ports]]
name = "http"
container_port = 80

[integrations]
auth = []
smtp = false
