[service]
name = "ryra-registry"
description = "Static file server hosting the ryra service registry"
url = "https://ryra.dev"
architecture = ["amd64", "arm64"]

[requirements.ram]
min = 32
recommended = 64

[[ports]]
name = "http"
container_port = 80

[integrations]
auth = []
smtp = false
